import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Abderrezague ismail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
           <Navbar/>
           {children}
      </body>
    </html>

  );
}
